import t4tRoutes from '@common/node/t4t/index';
import express from 'express';
import * as auth from './auth/routes.ts';
import base from './base/routes.ts';
import categoriesRoute from './categories/routes.ts';
import fido from './fido/routes.ts';
import iamUsersRoute from './iam-users/routes.ts';
import rolesRoute from './roles/routes.ts';
import email from './sendgrid/routes.ts';
import emailTemplates from './sendgrid/template-routes.ts';
import emailWebhooks from './sendgrid/webhook-routes.ts';
import sse from './sse/routes.ts';
import tenantComms from './tenant-comms/routes.ts';
import tests from './tests/routes.ts';
import webhooks from './webhooks/routes.ts';
import webpush from './webpush/routes.ts';
import whatsapp from './whatsapp/routes.ts';
import whatsappTemplates from './whatsapp/template-routes.ts';

// Generated CRUD routes — add mounts here after running the relevant generate:crud script
// Each table gets a sidecar routes.ts (re-exports generated by default, add custom routes there)
// Example: import awardRoute from './award/routes.ts';
//          router.use('/award', awardRoute);

const router = express.Router();

// export your routes here - make sure no clashes
export default ({ app }) => {
  app.use(
    '/api/sample-api',
    router.use('/', base), // http://127.0.0.1:3000/api/sample-api/
    router.use('/categories', categoriesRoute), // http://127.0.0.1:3000/api/sample-api/categories/
    router.use('/iam-users', iamUsersRoute), // http://127.0.0.1:3000/api/sample-api/iam-users/
    router.use('/roles', rolesRoute), // http://127.0.0.1:3000/api/sample-api/roles/
    router.use('/webhooks', webhooks),
    router.use('/whatsapp', whatsapp), // http://127.0.0.1:3000/api/sample-api/whatsapp/webhook
    router.use('/whatsapp/templates', whatsappTemplates), // http://127.0.0.1:3000/api/sample-api/whatsapp/templates
    router.use('/sendgrid', email), // http://127.0.0.1:3000/api/sample-api/sendgrid/test
    router.use('/sendgrid/templates', emailTemplates), // http://127.0.0.1:3000/api/sample-api/sendgrid/templates
    router.use('/sendgrid', emailWebhooks), // http://127.0.0.1:3000/api/sample-api/sendgrid/inbound + /events
    router.use('/tenant-comms', tenantComms), // http://127.0.0.1:3000/api/sample-api/tenant-comms
    router.use('/sse', sse),
    router.use('/tests', tests), // for tests
    router.use('/webpush', webpush),
    router.use('/fido', fido),
  );

  t4tRoutes({ app, routePrefix: '/api/t4t' }); // http://127.0.0.1:3000/api/t4t/

  // authentication stuff Below - you can remove if not needed (be aware of routing if you are customizing your auth)
  // routes used are: /api/auth (own auth rollout), /api/oauth, /api/oidc, /api/saml
  // this one can actually be a microservice on its own, but for demo purposes we are putting it here
  app.use(
    '/api',
    router.use('/auth', auth.myauthRoute),
    router.use('/oidc', auth.oidcRoute),
    router.use('/oauth', auth.oauthRoute),
    router.use('/saml', auth.samlRoute),
  );
};
