import type { T4tTableConfig } from '@common/node/t4t/types';

export default {
  name: 'student',
  conn: 'drizzle1',
  displayName: 'Student',
  view: 'admin,editor,viewer',
  create: 'admin',
  update: 'admin,editor',
  delete: 'admin',
  import: 'admin,editor',
  export: 'admin,editor',
  deleteLimit: 1,
  multiSelect: false,
  cols: {
    id: { label: 'Id', auto: 'pk', edit: 'readonly' },
    firstName: { label: 'First Name', type: 'string', add: true, edit: true, filter: true, ui: { tag: 'input' } },
    lastName: { label: 'Last Name', type: 'string', add: true, edit: true, filter: true, ui: { tag: 'input' } },
    avatar: { label: 'Avatar', type: 'string', add: true, edit: true, filter: true, ui: { tag: 'input' } },
    kyc: { label: 'Kyc', type: 'string', add: true, edit: true, filter: true, ui: { tag: 'input' } },
    awards: { label: 'Awards', type: 'string', add: true, edit: true, filter: true, ui: { tag: 'input' } },
    sex: { label: 'Sex', type: 'string', add: true, edit: true, filter: true, ui: { tag: 'input' } },
    age: { label: 'Age', type: 'integer', add: true, edit: true, filter: true },
    gpa: { label: 'Gpa', type: 'decimal', add: true, edit: true, filter: true },
    birthDate: { label: 'Birth Date', type: 'date', add: true, edit: true, filter: true },
    birthTime: { label: 'Birth Time', type: 'time', add: true, edit: true, filter: true },
    country: { label: 'Country', type: 'string', add: true, edit: true, filter: true, ui: { tag: 'input' } },
    state: { label: 'State', type: 'string', add: true, edit: true, filter: true, ui: { tag: 'input' } },
    dateTimeTz: { label: 'Date Time Tz', type: 'datetime', add: true, edit: true, filter: true },
    secret: { label: 'Secret', type: 'string', add: true, edit: true, filter: true, ui: { tag: 'input' } },
    remarks: { label: 'Remarks', type: 'string', add: true, edit: true, filter: true, ui: { tag: 'input' } },
    updated_by: { label: 'Updated_by', type: 'string', add: true, edit: true, filter: true, ui: { tag: 'input' } },
    updated_at: { label: 'Updated_at', type: 'datetime', add: true, edit: true, filter: true },
  },
} satisfies T4tTableConfig;
