import type { T4tTableConfig } from '@common/node/t4t/types';

export default {
  name: 'users',
  conn: 'drizzle1',
  displayName: 'Users',
  view: 'admin,editor,viewer',
  create: 'admin',
  update: 'admin,editor',
  delete: 'admin',
  import: 'admin,editor',
  export: 'admin,editor',
  deleteLimit: 1,
  multiSelect: false,
  cols: {
    id: { label: 'Id', auto: 'pk', edit: 'readonly' },
    roles: { label: 'Roles', type: 'string', add: true, edit: true, filter: true, ui: { tag: 'input' } },
    tenant_id: { label: 'Tenant_id', type: 'integer', add: true, edit: true, filter: true },
    username: { label: 'Username', type: 'string', add: true, edit: true, filter: true, ui: { tag: 'input' } },
    email: {
      label: 'Email',
      type: 'string',
      required: true,
      add: true,
      edit: true,
      filter: true,
      ui: { tag: 'input' },
    },
    githubId: { label: 'Github Id', type: 'integer', add: true, edit: true, filter: true },
    password: { label: 'Password', type: 'string', add: true, edit: true, filter: true, ui: { tag: 'input' } },
    salt: { label: 'Salt', type: 'string', add: true, edit: true, filter: true, ui: { tag: 'input' } },
    role: { label: 'Role', type: 'string', add: true, edit: true, filter: true, ui: { tag: 'input' } },
    retryLimit: { label: 'Retry Limit', type: 'integer', add: true, edit: true, filter: true },
    retryCount: { label: 'Retry Count', type: 'integer', add: true, edit: true, filter: true },
    retryReset: { label: 'Retry Reset', type: 'integer', add: true, edit: true, filter: true },
    gaKey: { label: 'Ga Key', type: 'string', add: true, edit: true, filter: true, ui: { tag: 'input' } },
    pnToken: { label: 'Pn Token', type: 'string', add: true, edit: true, filter: true, ui: { tag: 'input' } },
    revoked: { label: 'Revoked', type: 'string', add: true, edit: true, filter: true, ui: { tag: 'input' } },
    refreshToken: { label: 'Refresh Token', type: 'string', add: true, edit: true, filter: true, ui: { tag: 'input' } },
    sms: { label: 'Sms', type: 'string', add: true, edit: true, filter: true, ui: { tag: 'input' } },
    smsLastSent: { label: 'Sms Last Sent', type: 'datetime', add: true, edit: true, filter: true },
    smsOtpPin: { label: 'Sms Otp Pin', type: 'string', add: true, edit: true, filter: true, ui: { tag: 'input' } },
    smsVerified: { label: 'Sms Verified', type: 'integer', add: true, edit: true, filter: true },
    telegramId: { label: 'Telegram Id', type: 'string', add: true, edit: true, filter: true, ui: { tag: 'input' } },
    telegramUsername: {
      label: 'Telegram Username',
      type: 'string',
      add: true,
      edit: true,
      filter: true,
      ui: { tag: 'input' },
    },
  },
} satisfies T4tTableConfig;
